//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetitionLetter.Dll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerLeader
    {
        public int Id { get; set; }
        public int LedgerId { get; set; }
        public string Name { get; set; }
        public string Duty { get; set; }
        public string Phone { get; set; }
        public int Type { get; set; }
    }
}
