//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetitionLetter.Dll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeReceiver
    {
        public int Id { get; set; }
        public int NoticeId { get; set; }
        public int Receiver { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public int Status { get; set; }
    }
}
