//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetitionLetter.Dll.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetitionLetterEntities : DbContext
    {
        public PetitionLetterEntities()
            : base("name=PetitionLetterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<County> County { get; set; }
        public virtual DbSet<NoticeReceiver> NoticeReceiver { get; set; }
        public virtual DbSet<Warning> Warning { get; set; }
        public virtual DbSet<TownCoordinate> TownCoordinate { get; set; }
        public virtual DbSet<Ledger> Ledger { get; set; }
        public virtual DbSet<LedgerLeader> LedgerLeader { get; set; }
        public virtual DbSet<Petition> Petition { get; set; }
        public virtual DbSet<WarningFlow> WarningFlow { get; set; }
    }
}
